### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by cclauss** [ctf-wiki/ctf-wiki#61]
See https://github.com/ctf-wiki/ctf-wiki/issues/42#issuecomment-323586400

Where is the dependency list?  Which dependencies are not yet Python 3 compatible?

**Comment by iromise** [comment]
Sorry, here something I said was wrong, not package, actually some code, mainly caused by the `print`  function.  

>  since there is still a lot package dependency whose version is Python 2.7

So there is no dependency list... And as far as I think, possibly not right, if you can not run the given code, the message given by the system could help you solve it, this should be easy. And If we give two files(or judge in the file) in one problem, this may also be redundant. What's your opinion?

**Comment by cclauss** [comment]
The __2to3__ utility that ships with Python can automatically all print statements for you so that they are compatible with both Python 2 and Python 3.

You can run `2to3 -f print .` when at the root of the project to see all the lines that need to be changed and then you can run `2to3 -f print -w .` to actually write the changes.

https://docs.python.org/2/library/2to3.html

**Comment by iromise** [comment]
Thanks a lot, first time to see this command. And since so, maybe one version is enough as `3to2` also exists?

**Comment by cclauss** [comment]
Yes https://pypi.python.org/pypi/3to2 exists but I doubt that you would use it.  The changes that I mention above will be compatible with both Py2 and Py3.

**Comment by iromise** [comment]
Yes, now I won't use it since I think this is not necessary as people who read this doc should have the ability to solve the conflict between Py2 and Py3.
