### ISSUE TITLE
关于chunk大小的分析。

### ISSUE THREAD

**Issue by dc198488** [ctf-wiki/ctf-wiki#781]
关于 chunk 的大小，包括ctf-wiki以及我能找到的所有视频对chunk大小的描写差不多，无非就是根据 x86 或 x64 有所不同，其大小必须是 2 * SIZE_SZ 的整数倍。如果申请的内存大小不是 2 * SIZE_SZ 的整数倍，会被转换满足大小的最小的 2 * SIZE_SZ 的倍数。32 位系统中，SIZE_SZ 是 4；64 位系统中，SIZE_SZ 是 8。但在  x86 系统下   >=glibc2.26 版本的情况下，大小并非像教程中所写的一样。
以下是我写的分析内容，如有不妥，请指正。
https://www.freebuf.com/articles/system/272335.html

**Comment by arttnba3** [comment]
Hi dc198488,

Thanks for reaching out the CTF-wiki team and thank you for your feedback. This issue was fixed in #915 , and this issue is going to be closed. This is just a notification message, so you don't need to take any extra actions.

If you have any further concerns, or if you have any other thoughts, please feel free to contact us at your earliest convenience.

Yours sincerely,
arttnba3
CTF-wiki team
30/09/2024
