### ISSUE TITLE
关于 Theme Color 的问题

### ISSUE THREAD

**Issue by Dup4** [ctf-wiki/ctf-wiki#808]
OS Version: Mac OS X 10.15.7(19H1417)
Browser Version: Google Chrome 93.0.4577.82（正式版本） (x86_64)

系统的主题是：深色主题

现象：

在切换页面的时候，CTF-Wiki 的主题会有一个人眼可感知的切换过程，而且从明到暗的切换会让人感到不适

https://user-images.githubusercontent.com/38343778/135008196-1aca0575-feb2-4c92-9034-2f4d623912a8.mp4

**Comment by arttnba3** [comment]
Hi Dup4,

Thanks for reaching out CTF-wiki team. Unfortunately we don't have any related plans to change such features recently, and this issue is going to be closed. This is just a notification message, so you don't need to take any extra actions.

If you have any further concerns, or if you have some other thoughts, please feel free to contact us.

Best regards,
arttnba3
30/09/2024
