### ISSUE TITLE
pyc 文件结构的描述过时

### ISSUE THREAD

**Issue by FantasqueX** [ctf-wiki/ctf-wiki#820]
在 python 3.9.7 环境下，pyc文件的头部占16个字节，有两种可能的结构，分别是记录时间和哈希，而不是现在wiki里写的占8个字节。

**Comment by iromise** [comment]
欢迎 PR ~

**Comment by arttnba3** [comment]
Hi FantasqueX,

Thanks for reaching out the CTF-wiki team and thank you for your feedback. This issue was fixed in #915  , and this issue is going to be closed. This is just a notification message, so you don't need to take any extra actions.

If you have any further concerns, or if you have any other thoughts, please feel free to contact us at your earliest convenience.

Yours sincerely,
arttnba3
CTF-wiki team
30/09/2024
