### ISSUE TITLE
本地部署后搜索引擎不起作用， 我看线上版本也不支持模糊查询，是我操作有问题还是本身就不支持

### ISSUE THREAD

**Issue by Francis-cw** [ctf-wiki/ctf-wiki#825]
![image](https://user-images.githubusercontent.com/93650445/142124038-138a30cb-c23a-40b9-aba1-06cebe8ffc37.png)

**Comment by iromise** [comment]
可以的，首次需要初始化，比较慢。

**Comment by arttnba3** [comment]
Hi Francis-cw,

Thanks for reaching out the CTF-wiki team and thank you for your feedback. As it's been a while without your new replys since our last communication, this issue is going to be closed. This is just a notification message, so you don't need to take any extra actions.

If you have any further concerns, or if you have any other thoughts, please feel free to contact us at your earliest convenience.

Yours sincerely,
arttnba3
CTF-wiki team
30/09/2024
