### ISSUE TITLE
位于 android/basic_operating_mechanism/java_layer/smali/smali 的 typo

### ISSUE THREAD

**Issue by NKID00** [ctf-wiki/ctf-wiki#844]
[Smali](https://ctf-wiki.org/android/basic_operating_mechanism/java_layer/smali/smali/) 这一章的 [变量类型](https://ctf-wiki.org/android/basic_operating_mechanism/java_layer/smali/smali/#_7) 一节：

> 注：所谓全名就是它的**全程**不仅仅是简写，比如 String 其实是 java.lang.String。

应为

> 注：所谓全名就是它的**全称**不仅仅是简写，比如 String 其实是 java.lang.String。

**Comment by iromise** [comment]
谢谢~欢迎提交 PR 进行修改。

**Comment by arttnba3** [comment]
Hi NKID00,

Thanks for reaching out the CTF-wiki team and thank you for your feedback. This issue was fixed in #915  , and this issue is going to be closed. This is just a notification message, so you don't need to take any extra actions.

If you have any further concerns, or if you have any other thoughts, please feel free to contact us at your earliest convenience.

Yours sincerely,
arttnba3
CTF-wiki team
30/09/2024
