### ISSUE TITLE
windows stack overflow example lose a include declaration

### ISSUE THREAD

**Issue by Mz1z** [ctf-wiki/ctf-wiki#862]
on page: https://ctf-wiki.org/pwn/windows/stackoverflow/stackoverflow-basic/
![image](https://user-images.githubusercontent.com/91617089/225653134-1287f31a-c82c-4d97-a7da-c145bca24c1e.png)
There a <strings.h> is needed to correctly compile.

**Comment by arttnba3** [comment]
Hi Mz1z,

This bug was fixed by you in PR #862 and #863 , and this issue is going to be closed. This is just a notification message, and you don't need to take any further actions to respond.

If you have any further concerns, please feel free to contact us.

Yours sincerely,
arttnba3
CTF-wiki team
29/09/2024
